/**
 * Generator for globals.d.ts file
 * Creates global TypeScript definitions with references to all packages and classes
 */

const fs = require('fs');
const path = require('path');

/**
 * Generate globals.d.ts with references to elasticsearch, packages, and classes
 * @param {string} rootPath - Root directory path (sydle-dev)
 */
function generateGlobalsDts(rootPath) {
    const globalsDtsPath = path.join(rootPath, 'globals.d.ts');
    let globalsDtsContent = `/**
 * Global type definitions - references all package and class definitions
 * Auto-generated by Sydle CLI
 */

`;

    // Add reference to Elasticsearch types
    globalsDtsContent += `/// <reference path="./elasticsearch.d.ts" />

`;

    // Find all package.d.ts and class.d.ts files and add triple-slash references
    if (fs.existsSync(rootPath)) {
        const packages = fs.readdirSync(rootPath);
        packages.forEach(pkg => {
            const pkgPath = path.join(rootPath, pkg);
            if (fs.existsSync(pkgPath) && fs.statSync(pkgPath).isDirectory()) {
                // Reference package.d.ts
                const packageDts = path.join(pkgPath, 'package.d.ts');
                if (fs.existsSync(packageDts)) {
                    globalsDtsContent += `/// <reference path="./${pkg}/package.d.ts" />
`;
                }

                // Reference all class.d.ts files in this package
                const classes = fs.readdirSync(pkgPath);
                classes.forEach(className => {
                    const classPath = path.join(pkgPath, className);
                    const classDts = path.join(classPath, 'class.d.ts');
                    if (fs.existsSync(classPath) && fs.statSync(classPath).isDirectory() && fs.existsSync(classDts)) {
                        globalsDtsContent += `/// <reference path="./${pkg}/${className}/class.d.ts" />
`;
                    }
                });
            }
        });
    }

    globalsDtsContent += `
`;
    fs.writeFileSync(globalsDtsPath, globalsDtsContent);
    console.log(`Generated globals.d.ts in ${rootPath}`);
}

module.exports = {
    generateGlobalsDts
};
