const fs = require('fs');
const path = require('path');

/**
 * Generate metadata.d.ts for _getMetadata methods
 * @param {string} scriptsFolderPath - Path to the scripts folder
 * @param {Object} classData - The full class JSON object
 */
function generateMetadataFiles(scriptsFolderPath, classData) {
    if (!classData || !classData.fields) return;

    const metadataDtsPath = path.join(scriptsFolderPath, 'metadata.d.ts');

    const content = `/**
 * Metadata definitions for _getMetadata script
 * Generated by Sydle CLI
 */

// Basic types
type I18nString = string | { [key: string]: string };

interface I_FieldMetadata {
    // Common properties
    name?: I18nString;
    hidden?: boolean;

    // Non-system fields
    required?: boolean;
    breakLine?: boolean;
    readOnly?: boolean;
    size?: 'lg' | 'md' | 'sm';
    
    // Additional Configs
    additionalConfigs?: {
        [key: string]: any;
    };
    exhibitionConfigs?: {
        [key: string]: any;
    };

    // Multiple fields
    minMultiplicity?: number;
    maxMultiplicity?: number;
    shiftable?: boolean;
    
    // Text fields
    maxLength?: number;
    mask?: any; // Reference to mask
    placeholder?: I18nString;
    
    // Decimal/Number fields
    decimalPrecision?: number;
    thousandSeparator?: boolean;
    
    // Dynamic/Reference fields
    query?: string | object;
    
    // Fields with value options (Decimal, Dynamic, Number, Long, Text)
    valueOptions?: {
        push(option: { identifier: string | number, value: string } | string): void;
        indexOf(option: { identifier: string | number }): number;
        pop(): { identifier: string | number, value: string } | string | undefined;
        splice(start: number, deleteCount: number): void;
        length: number;
        [index: number]: any;
    };

    // Dynamic fields
    type?: "REFERENCE" | "FILE" | "DOUBLE" | "STRING" | "BOOLEAN" | "DATE" | "INTEGER" | "LONG" | "ID" | "GEOPOINT";
    multiple?: boolean;
    i18n?: boolean;
    embedded?: boolean;
    refClass?: { _id: string, _classId?: string } | string;

    // File fields
    signers?: Array<{ _id: string, classId: string }>;
    visualSignatureSettings?: {
        text?: string;
        image?: string;
        x?: number;
        y?: number;
        width?: number;
        height?: number;
        fontSize?: number;
        page?: number;
    };
    acceptedExtensions?: string[];
    enableSigning?: boolean;
    includeVisualSignature?: boolean;
    signatureLocations?: Array<{
        name: string;
        sign: string;
        signAt: string;
        signBefore?: string;
    }>;
    maxSize?: number;
    pdfSignFormat?: { _id: string, _classId: string };
    signatureLocationChoice?: 'All' | 'OnlyOne' | 'OneOrMore';
    
    // Embedded Reference Items
    items?: {
        findById(id: string): I_EmbeddedItemMetadata;
        [id: string]: I_EmbeddedItemMetadata | any;
    };

    [key: string]: any;
}

interface I_EmbeddedItemMetadata {
    hidden?: boolean;
    removable?: boolean;
    [key: string]: any;
}

interface I_MetadataFields {
${classData.fields.map(field => `    ${field.identifier}: I_FieldMetadata;`).join('\n')}
}

declare interface I_Metadata {
    editHelp?: I18nString;
    context?: {
        _disableRequired?: boolean;
    };
    concreteClasses?: Array<{ _id: string }>;
    fields: I_MetadataFields;
}

declare var _metadata: I_Metadata;
`;

    fs.writeFileSync(metadataDtsPath, content);
}

module.exports = {
    generateMetadataFiles
};
